%% Dependence of equilibrium on R and chi
clear
clc

s=1/3;
del=1/2;
R=1:0.001:5;
chi=0.001:0.001:2;

[R1,chi1]=meshgrid(R,chi);
m=chi1-s-1;
n=4*s*(R1-1);
x=m+1+sqrt(m.^2+n);

T2eqn=(1-x.^2)./4./s./R1;
qeqn=(x-1)./2./s;
h1eqn=chi1.*qeqn./R1;
T1minusT2=qeqn./R1;

blueOrangeRed=[0.00,0.00,0.45;...
               0.00,0.18,0.70;...
               0.08,0.36,0.86;...
               0.25,0.52,0.96;...
               0.48,0.73,0.95;...
               0.72,0.90,0.96;...
               1.00,0.93,0.70;...
               0.99,0.72,0.42;...
               0.96,0.46,0.18;...
               0.80,0.20,0.02;...
               0.58,0.04,0.00;...
               0.35,0.00,0.00];

fig=figure('Color','w','Units','pixels','Position',[100,100,1020,640]);
tiledlayout(fig,2,2,'TileSpacing','compact','Padding','compact');

T2clim=[min(T2eqn(:)),max(T2eqn(:))];
drawFilledPanel(nexttile,T2eqn,T2clim,linspace(T2clim(1),T2clim(2),12),...
    '(a) Nondimensional EP SST (T2*)',R1,chi1,blueOrangeRed);

drawFilledPanel(nexttile,T1minusT2,[0,2],linspace(0,2,12),...
    '(b) Nondimensional SST diff (T1*-T2*)',R1,chi1,blueOrangeRed);

drawFilledPanel(nexttile,qeqn,[0,4.6],linspace(0,4.6,12),...
    '(c) Nondimensional upwelling (q*)',R1,chi1,blueOrangeRed);

drawFilledPanel(nexttile,h1eqn,[0,4],linspace(0,4,12),...
    '(d) Nondimensional WP thermocline depth (\eta1*)',R1,chi1,blueOrangeRed);

function drawFilledPanel(ax,Z,climRange,cbTicks,titleText,R1,chi1,cmap)
    Zplot=Z;
    Zplot(Zplot<climRange(1))=climRange(1);
    Zplot(Zplot>climRange(2))=climRange(2);

    levels=linspace(climRange(1),climRange(2),size(cmap,1)+1);
    contourf(ax,R1,chi1,Zplot,levels,'LineStyle','none');
    axis(ax,[1,5,0,2]);
    caxis(ax,climRange);
    colormap(ax,cmap);

    cb=colorbar(ax);
    set(cb,'Ticks',cbTicks,...
        'TickLabels',compose('%.1f',cbTicks),...
        'FontSize',12,...
        'FontName','Times New Roman');

    title(ax,titleText,...
        'Interpreter','tex',...
        'FontName','Times New Roman',...
        'FontSize',13,...
        'FontWeight','bold');
    set(ax,...
        'FontSize',12,...
        'FontName','Times New Roman',...
        'Box','on',...
        'Layer','top',...
        'LineWidth',0.8,...
        'TickDir','in');
    xticks(ax,1:5);
    yticks(ax,0:0.5:2);
    xlabel(ax,'R','FontName','Times New Roman','FontSize',14,'FontAngle','italic');
    ylabel(ax,'\chi','Interpreter','tex','FontName','Times New Roman','FontSize',14,'FontAngle','italic');
end
